logging:
  level:
    root: INFO
spring:
  application:
    name: rest-jwt-app
---
server:
  port: 3001
#  ssl:
#    enabled: true
    #    client-auth: need
#    key-store: classpath:secrets/rest-server-keystore.p12
#    key-store-password: changeit
#    key-alias: rest-server
#    key-store-type: PKCS12
#    trust-store: classpath:secrets/rest-server-keystore.jks
#    trust-store-password: changeit
#    trust-store-type: JKS

---
#jwt:
#  ssl:
#    enabled: false
